<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOMCY2tM\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOMCY2tM/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOMCY2tM.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOMCY2tM\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOMCY2tM\App_KernelDevDebugContainer([
    'container.build_hash' => 'OMCY2tM',
    'container.build_id' => '07112983',
    'container.build_time' => 1741882079,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOMCY2tM');
